### ISSUE TITLE
GCD Bar With Spell Name Issue

### ISSUE THREAD

**Issue by chesme** [voidzone/Gnosis#2]
Seems that tick damage of spirit bomb overlaps whatever is displayed on current gcd/castbar.

**Comment by voidzone** [comment]
Have no idea what you're talking about and I'm not seeing any issues with Spirit Bomb on my DH.

**Comment by chesme** [comment]
https://gyazo.com/b99f61c106e4d3e235059b5c815028b3 preview (on gif 2nd spell i cast was spirit bomb, never casted it again in this gif)
https://pastebin.com/t7VmCkCT bar export

**Comment by voidzone** [comment]
Interesting.  I'll take a look later and see what I can figure out.

**Comment by voidzone** [comment]
Should hopefully be fixed in v4.67

**Comment by chesme** [comment]
Just an update - issue is still there, kinda used to it. Sorting brewmaster UI now and same thing is happening with Rushing Jade Wind (while active it overlaps any other cast).

Maybe it is an issue on my bar config, if noone else have the same problem? Mind to test/check?

**Comment by voidzone** [comment]
I'm able to duplicate the issue with your bar, just don't have any idea why it would be switching the spell name mid-bar.

That said, you're the first person I've seen whose added text to the GCD bar.
This is my GCD bar:
https://pastebin.com/STN9QHUK

**Comment by voidzone** [comment]
Actually scratch that, looks like each tick of the soulbomb is triggering UNIT_SPELLCAST_SUCCEEDED

Which... ya.

**Comment by voidzone** [comment]
Spoke with Gnosis' creator and he recommended the following:

> 
> A quick fix to make sure the GCD bar is hidden while another bar is active is by using a global cooldown timer bar (instead of a “Castbar” GCD bar). From my shadow priest configuration:
> 
> -- global cooldown
> gcd hidden="GnCB_Player" : any
> 
> Any global cooldown will be shown as long as the castbar (named GnCB_Player) is currently not active.

**Comment by voidzone** [comment]
Should be fixed in v4.70
Looks like Blizzard fixed GetSpellCooldown() so it returned the GCD for all spells now and not the GCD spell only.  It was using the GCD spell that was causing the bar to refresh with the name of spells other than the one currently being cast.

**Comment by Stanzilla** [comment]
@voidzone can you clarify what exactly changed with GetSpellCooldown()?

**Comment by voidzone** [comment]
When the pre-patch launched spells werent returning the GCD so in order to make the GCD bar work at all I had to switch it over to pulling from https://www.wowhead.com/spell=61304/global-cooldown

So any time a tick of Spirit Bomb or Icicles etc. would go off it'd check for the GCD of the GCD spell then override the name on the GCD bar midway through.  Now that it's back to where the spells themselves are giving the GCD value they don't provide a value unless they're infact triggering the GCD so Spirit Bomb etc. wont trigger an update to the GCD bar.

**Comment by Stanzilla** [comment]
I see, thanks!

**Comment by voidzone** [comment]
Will be deleting this repo once you've confirmed the issue's resolved. @chesme

**Comment by chesme** [comment]
This is fixed, thanks a lot
